title: Xemantic
description: applied philosophy collective
url: "https://xemantic.com"
baseurl: ""

render_drafts: true
unpublished: true
# This tells Jekyll to process even files without front matter

# Build settings
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown
  parse_block_html: true
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - "*.md"
  - "**/*.md"

# Exclude from processing
exclude:
  - .idea/
  - README.md
  - TODO.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor

defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default" # Set default layout
