title: Xemantic
description: applied philosophy collective
url: "https://xemantic.com"
baseurl: ""

render_drafts: true
unpublished: true
# This tells Jekyll to process even files without front matter

# Build settings
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown
  hard_wrap: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-loading-lazy
  - jekyll-email-protect

include:
  - "*.md"
  - "**/*.md"

# Exclude from processing
exclude:
  - .idea/
  - README.md
  - TODO.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor

defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default" # Set default layout

titles_from_headings:
  enabled: true
  collections: true

safe: false  # This must be false to allow plugins
plugins_dir: _plugins  # This is the default directory for plugins
