/*
 * Copyright 2026 Kazimierz Pogoda / Xemantic
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.xemantic.website

import com.xemantic.markanywhere.SemanticEvent
import com.xemantic.markanywhere.flow.semanticEvents
import com.xemantic.markanywhere.transform.transform
import kotlinx.coroutines.flow.Flow

/**
 * The BeerCSS modules and the Material Symbols icons the site uses,
 * generated by `./gradlew generateBeerCss`, see `build.gradle.kts`.
 */
private const val BEER_CSS = "/assets/css/beercss.css"

/**
 * Sets BeerCSS's `dark` or `light` class on `body` from the color scheme
 * preference, the only thing `beer.loader.js` would do on this site.
 * Being the first child of `body`, it runs before the first paint,
 * so a dark mode page never flashes light.
 */
private const val COLOR_SCHEME_SCRIPT =
    "document.body.classList.add(matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')"

private const val XEMANTIC_CSS = "/assets/css/xemantic.css"

private const val GITHUB_URL = "https://github.com/xemantic"

private const val GITHUB_ICON =
    "/assets/images/github/GitHub_Invertocat_Black.svg"

/**
 * The site-wide copyright line. Kept brand-level on purpose: the precise
 * legal entity behind "Xemantic" is disclosed in the `/impressum/` page,
 * so this notice needs no change when that entity formalizes.
 */
internal const val COPYRIGHT = "© 2026 Xemantic"

/**
 * The license of the site content. The exceptions, like the images and
 * the hosted works of other authors, are listed in the repository's
 * `REUSE.toml`, hence the "unless stated otherwise".
 */
private const val CONTENT_LICENSE = "CC BY 4.0"

private const val CONTENT_LICENSE_URL =
    "https://creativecommons.org/licenses/by/4.0/"

/**
 * The [COPYRIGHT] and the [CONTENT_LICENSE] as a Markdown footer, appended
 * to every verbatim `.md` document that is served, separated from the
 * content by a thematic break. It carries no Impressum link, unlike the
 * rendered pages' footer: a plain source file is not the place for site
 * navigation.
 */
internal const val MARKDOWN_COPYRIGHT_FOOTER =
    "\n\n---\n\n$COPYRIGHT · Content licensed under " +
        "[$CONTENT_LICENSE]($CONTENT_LICENSE_URL) unless stated otherwise\n"

/**
 * Applies the xemantic.com page layout: the `head` is completed with
 * `charset`/`viewport` metas, the [BEER_CSS] and the xemantic.com
 * stylesheets, the `body` content is prefixed with the
 * [COLOR_SCHEME_SCRIPT] and a top app bar (`header` with `nav`), the `main` element (synthesized
 * by [wrapBodyContentInMain]) becomes BeerCSS's `main.responsive`
 * container, the table of contents `nav` is wrapped in an `aside`, and
 * the `body` is closed with a `footer` carrying the [COPYRIGHT] notice
 * and a link to the Impressum.
 */
fun Flow<SemanticEvent>.applyPageLayout() = transform {

    match("head") {
        "head" {
            "meta"("charset" to "utf-8") {}
            "meta"(
                "name" to "viewport",
                "content" to "width=device-width, initial-scale=1"
            ) {}
            children()
            "link"("href" to BEER_CSS, "rel" to "stylesheet") {}
            "link"("href" to XEMANTIC_CSS, "rel" to "stylesheet") {}
        }
    }

    match("body") {
        "body" {
            "script" { +COLOR_SCHEME_SCRIPT }
            "header"("class" to "fixed") {
                "nav" {
                    "a"("href" to "/", "class" to "circle transparent") {
                        "i" { +"home" }
                    }
                    "h5"("class" to "max") { +"xemantic" }
                    "a"(
                        "href" to GITHUB_URL,
                        "class" to "circle transparent",
                        "aria-label" to "Xemantic on GitHub"
                    ) {
                        "img"(
                            "class" to "github-icon",
                            "src" to GITHUB_ICON,
                            "alt" to "GitHub"
                        ) {}
                    }
                }
            }
            children()
            "footer" {
                "nav" {
                    "span"("class" to "max") {
                        +"$COPYRIGHT · Content licensed under "
                        "a"("href" to CONTENT_LICENSE_URL, "rel" to "license") {
                            +CONTENT_LICENSE
                        }
                        +" unless stated otherwise"
                    }
                    "a"("href" to "/impressum/") { +"Legal Notice (Impressum)" }
                }
            }
        }
    }

    match("main") {
        "main"("class" to "responsive") {
            children()
        }
    }

    passthrough()

}

/**
 * Wraps the direct content of `body` in a `main` element, up to the trailing
 * `nav` with `id="toc"` (emitted at the very end of the stream by
 * `wrapInSections`), which gets an `aside` of its own, a sibling of `main`.
 * On a page without a table of contents `main` simply closes together with
 * `body`.
 *
 * Applied *after* `wrapInHtmlDocument`, never before: that operator moves the
 * front matter into the `head` only when the `frontmatter` mark opens the
 * stream, so nothing may emit a mark ahead of it.
 */
fun Flow<SemanticEvent>.wrapBodyContentInMain(): Flow<SemanticEvent> = semanticEvents {
    var wrapper: String? = null
    collect { event ->
        when {
            event is SemanticEvent.Mark && event.name == "body" -> {
                emit(event)
                mark("main")
                wrapper = "main"
            }
            wrapper != null && event is SemanticEvent.Mark
                && event.name == "nav" && event["id"] == "toc" -> {
                unmark(wrapper!!)
                mark("aside")
                wrapper = "aside"
                emit(event)
            }
            event is SemanticEvent.Unmark && event.name == "body" -> {
                wrapper?.let { unmark(it) }
                wrapper = null
                emit(event)
            }
            else -> emit(event)
        }
    }
}
