[versions]
kotlinTarget = "2.4"
javaTarget = "17"
kotlin = "2.4.20"
# libraries
kotlinxCoroutines = "1.11.0"
kotlinxIo = "0.9.1"
ktor = "3.6.0"
markanywhere = "0.4.0"
xemanticKotlinCore = "0.9.0"
# web, downloaded by the generateBeerCss task
beerCss = "5.0.3"
# plugins
versionCatalogUpdatePlugin = "1.1.1"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
markanywhere-parse = { module = "com.xemantic.markanywhere:markanywhere-parse", version.ref = "markanywhere" }
markanywhere-render = { module = "com.xemantic.markanywhere:markanywhere-render", version.ref = "markanywhere" }
markanywhere-transform = { module = "com.xemantic.markanywhere:markanywhere-transform", version.ref = "markanywhere" }
markanywhere-html = { module = "com.xemantic.markanywhere:markanywhere-html", version.ref = "markanywhere" }
xemantic-kotlin-core = { module = "com.xemantic.kotlin:xemantic-kotlin-core", version.ref = "xemanticKotlinCore" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
